### ISSUE TITLE
Environment variable support in docker-compose issue

### ISSUE THREAD

**Issue by DenisNovac** [Percona-Lab/clickhouse_exporter#4]
I've tried to do change Dockerfile with this:

`CMD ["-scrape_uri=${SCRAPE_URI}"]`

My compose:
```
clickhouse_exporter:
    container_name: exporter
    image: percona-lab/clickhouse_exporter
    depends_on:
      - "clickhouse"
    restart: always
    networks:
      ch_back:
        ipv4_address: 172.18.0.4
    ports: 
      - 9116:9116
    environment:
      - SCRAPE_URI=http://172.18.0.2:8123
```

And i get this error:

> exporter               | time="2020-01-14T04:25:40Z" level=info msg="Error scraping clickhouse: Error scraping clickhouse url $%7BSCRAPE_URI%7D?query=select+metric%2C+value+from+system.metrics: Error scraping clickhouse: Get $%7BSCRAPE_URI%7D?query=select+metric%2C+value+from+system.metrics: unsupported protocol scheme \"\"" file=exporter.go line=292
